if(EXISTS "/Users/jesshu/Desktop/oop-project/test_runner-b12d07c_tests.cmake")
  include("/Users/jesshu/Desktop/oop-project/test_runner-b12d07c_tests.cmake")
else()
  add_test(test_runner_NOT_BUILT-b12d07c test_runner_NOT_BUILT-b12d07c)
endif()
